import { ContentItem } from "@/types/content";

export const COPY_LIBRARY_PROMPTS: ContentItem[] = [
    {
        id: "sop-sales-page",
        type: "text_prompt",
        title: "SOP: Arquitectura de Página de Ventas (High-Ticket)",
        slug: "sop-arquitectura-de-pagina-de-ventas-high-ticket",
        summary: "Un sistema de redacción de conversión estructurado para vender ofertas de servicios, consultoría o infraestructuras complejas, asegurando que el diseño de la página responda a objeciones antes de que el cliente las formule.",
        body_markdown: `# SOP: Arquitectura de Página de Ventas (High-Ticket)\n\n## D.R.A.P.E.R.™ System Integration\n\n> **D - Diagnosticar:** Define claramente la oferta principal, el problema específico que resuelve (el dolor del cliente) y las 3 objeciones más comunes que escuchas en tus llamadas de venta.\n\n> **R - Rediseñar:** Extrae los testimonios, casos de éxito o métricas de garantía que respaldarán la promesa de la oferta.\n\n> **A - Arquitectar & Programar (El Prompt Maestro):** Inyecta la siguiente instrucción en Claude:\n>\n> \`\`\`\n> Eres un copywriter de conversión que escribe páginas de ventas para negocios de servicios y ofertas de alto valor. Escribe una página de ventas completa para la oferta que describiré a continuación. Estructúrala de la siguiente manera:\n> Un titular que hable directamente al problema principal.\n> Un subtítulo que introduzca el resultado.\n> Una sección que agite el problema con lenguaje específico y situaciones cotidianas.\n> Una sección que presente la oferta como la solución definitiva.\n> Un desglose técnico pero accesible de lo que está incluido.\n> Tres secciones de manejo de objeciones redactadas en formato FAQ.\n> Marcadores de posición para prueba social.\n> Sección de precios con un CTA claro y una sección de cierre que genere urgencia real.\n> [Inserta los datos de tu oferta, problema y objeciones aquí]\n> \`\`\`\n\n> **P - Encender:** Pasa el texto generado a tu constructor web (ej. el agente que utiliza el "Anti-AI Web Design Blueprint").\n\n> **R - Refinar:** Instala mapas de calor (ej. Hotjar) en la página publicada. Si los usuarios no llegan a la sección de precios, el titular o la sección de "agitación del problema" necesita más urgencia.`,
        prompt_text: `Eres un copywriter de conversión que escribe páginas de ventas para negocios de servicios y ofertas de alto valor. Escribe una página de ventas completa para la oferta que describiré a continuación. Estructúrala de la siguiente manera:\nUn titular que hable directamente al problema principal.\nUn subtítulo que introduzca el resultado.\nUna sección que agite el problema con lenguaje específico y situaciones cotidianas.\nUna sección que presente la oferta como la solución definitiva.\nUn desglose técnico pero accesible de lo que está incluido.\nTres secciones de manejo de objeciones redactadas en formato FAQ.\nMarcadores de posición para prueba social.\nSección de precios con un CTA claro y una sección de cierre que genere urgencia real.\n[Inserta los datos de tu oferta, problema y objeciones aquí]`,
        category: "Páginas de Ventas",
        level: "intermediate",
        is_published: true,
        is_featured: false,
        paywall_level: "free_preview",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        tags: [
            { id: "t-sop", name: "SOP", slug: "sop" },
            { id: "t-sales", name: "Sales", slug: "sales" },
            { id: "t-copywriting", name: "Copywriting", slug: "copywriting" }
        ]
    },
    {
        id: "fb-1",
        type: "text_prompt",
        title: "Identificación de la audiencia a la que se dirige",
        slug: "identificacion-audiencia-objetivo-facebook",
        summary: "Ensayo sobre la importancia de identificar la audiencia en marketing online.",
        body_markdown: "Escribe un ensayo que describa la importancia de identificar la audiencia a la que se dirige en una estrategia de marketing en línea. Incluye consejos prácticos sobre cómo identificar la audiencia adecuada y cómo adaptar la estrategia de marketing para llegar a esa audiencia.",
        prompt_text: "Escribe un ensayo que describa la importancia de identificar la audiencia a la que se dirige en una estrategia de marketing en línea. Incluye consejos prácticos sobre cómo identificar la audiencia adecuada y cómo adaptar la estrategia de marketing para llegar a esa audiencia.",
        category: "Marketing de Facebook",
        level: "beginner",
        is_published: true,
        is_featured: false,
        paywall_level: "free_preview",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        tags: [{ id: "t-facebook", name: "Facebook", slug: "facebook" }]
    },
    {
        id: "fb-2",
        type: "text_prompt",
        title: "Creación de buyer personas para comprender mejor a la audiencia",
        slug: "creacion-buyer-personas-marketing",
        summary: "Guía detallada sobre cómo crear buyer personas para negocios en línea.",
        body_markdown: "Escribe una guía detallada sobre cómo crear buyer personas para comprender mejor a la audiencia de un negocio en línea. Incluye los diferentes elementos que deben incluirse en una buyer persona, cómo utilizar la información obtenida y cómo adaptar la estrategia de marketing en función de los datos.",
        prompt_text: "Escribe una guía detallada sobre cómo crear buyer personas para comprender mejor a la audiencia de un negocio en línea. Incluye los diferentes elementos que deben incluirse en una buyer persona, cómo utilizar la información obtenida y cómo adaptar la estrategia de marketing en función de los datos.",
        category: "Marketing de Facebook",
        level: "beginner",
        is_published: true,
        is_featured: false,
        paywall_level: "free_preview",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        tags: [{ id: "t-facebook", name: "Facebook", slug: "facebook" }]
    },
    {
        id: "fb-3",
        type: "text_prompt",
        title: "Selección de opciones de segmentación adecuadas",
        slug: "segmentacion-adecuada-marketing-online",
        summary: "Artículo sobre cómo seleccionar opciones de segmentación para llegar a la audiencia deseada.",
        body_markdown: "Escribe un artículo que explique cómo seleccionar las opciones de segmentación adecuadas para llegar a la audiencia deseada en una estrategia de marketing en línea. Incluye consejos sobre cómo seleccionar las opciones de segmentación adecuadas, cómo utilizar las herramientas de segmentación disponibles y cómo adaptar la estrategia de marketing en función de los datos obtenidos.",
        prompt_text: "Escribe un artículo que explique cómo seleccionar las opciones de segmentación adecuadas para llegar a la audiencia deseada en una estrategia de marketing en línea. Incluye consejos sobre cómo seleccionar las opciones de segmentación adecuadas, cómo utilizar las herramientas de segmentación disponibles y cómo adaptar la estrategia de marketing en función de los datos obtenidos.",
        category: "Marketing de Facebook",
        level: "beginner",
        is_published: true,
        is_featured: false,
        paywall_level: "free_preview",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        tags: [{ id: "t-facebook", name: "Facebook", slug: "facebook" }]
    },
    {
        id: "fb-4",
        type: "text_prompt",
        title: "Establecimiento de objetivos de marketing",
        slug: "establecimiento-objetivos-marketing-online",
        summary: "Guía práctica para definir objetivos realistas y medibles.",
        body_markdown: "Escribe una guía práctica que describa cómo establecer objetivos de marketing para un negocio en línea. Incluye consejos sobre cómo definir objetivos realistas y alcanzables, cómo medir el éxito de los objetivos y cómo adaptar la estrategia de marketing en función de los datos obtenidos.",
        prompt_text: "Escribe una guía práctica que describa cómo establecer objetivos de marketing para un negocio en línea. Incluye consejos sobre cómo definir objetivos realistas y alcanzables, cómo medir el éxito de los objetivos y cómo adaptar la estrategia de marketing en función de los datos obtenidos.",
        category: "Marketing de Facebook",
        level: "beginner",
        is_published: true,
        is_featured: false,
        paywall_level: "free_preview",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        tags: [{ id: "t-facebook", name: "Facebook", slug: "facebook" }]
    },
    {
        id: "fb-5",
        type: "text_prompt",
        title: "Definición de una estrategia de contenido",
        slug: "estrategia-contenido-efectiva-facebook",
        summary: "Informe sobre cómo planificar y diseñar contenido para mejorar el marketing.",
        body_markdown: "Escribe un informe que describa cómo definir una estrategia de contenido efectiva para un negocio en línea. Incluye los diferentes tipos de contenido que se pueden utilizar, cómo identificar la audiencia adecuada, cómo planificar y diseñar el contenido y cómo utilizar el contenido para mejorar la estrategia de marketing.",
        prompt_text: "Escribe un informe que describa cómo definir una estrategia de contenido efectiva para un negocio en línea. Incluye los diferentes tipos de contenido que se pueden utilizar, cómo identificar la audiencia adecuada, cómo planificar y diseñar el contenido y cómo utilizar el contenido para mejorar la estrategia de marketing.",
        category: "Marketing de Facebook",
        level: "beginner",
        is_published: true,
        is_featured: false,
        paywall_level: "free_preview",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        tags: [{ id: "t-facebook", name: "Facebook", slug: "facebook" }]
    },
    {
        id: "fb-6",
        type: "text_prompt",
        title: "Planificación de campañas publicitarias",
        slug: "planificacion-campanas-publicitarias-exitosas",
        summary: "Guía detallada sobre canales, mensajes y medición de éxito publicitario.",
        body_markdown: "Escribe una guía detallada sobre cómo planificar campañas publicitarias efectivas para un negocio en línea. Incluye los diferentes elementos clave de una campaña publicitaria, cómo seleccionar los canales adecuados, cómo diseñar el mensaje de la campaña y cómo medir el éxito de la campaña.",
        prompt_text: "Escribe una guía detallada sobre cómo planificar campañas publicitarias efectivas para un negocio en línea. Incluye los diferentes elementos clave de una campaña publicitaria, cómo seleccionar los canales adecuados, cómo diseñar el mensaje de la campaña y cómo medir el éxito de la campaña.",
        category: "Marketing de Facebook",
        level: "beginner",
        is_published: true,
        is_featured: false,
        paywall_level: "free_preview",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        tags: [{ id: "t-facebook", name: "Facebook", slug: "facebook" }]
    },
    {
        id: "csv-1",
        type: "text_prompt",
        title: "Pie de foto para Instagram promocionando [tipo de producto]",
        slug: "pie-de-foto-instagram-promocion",
        summary: "Escribe un pie de foto de Instagram para un post promocional de [tipo de producto].",
        body_markdown: "Escribe un pie de foto de Instagram para un post promocional de [tipo de producto]. Utiliza un lenguaje amigable y humano que atraiga a [tipo de público]. Destaca las cualidades únicas de [tipo de producto], utiliza emojis de muestra y no suenes demasiado promocional.",
        prompt_text: "Escribe un pie de foto de Instagram para un post promocional de [tipo de producto]. Utiliza un lenguaje amigable y humano que atraiga a [tipo de público]. Destaca las cualidades únicas de [tipo de producto], utiliza emojis de muestra y no suenes demasiado promocional.",
        category: "Marketing y publicidad",
        level: "beginner",
        is_published: true,
        is_featured: false,
        paywall_level: "free_preview",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        tags: [{ id: "t-copy", name: "Copy", slug: "copy" }]
    },
    {
        id: "csv-2",
        type: "text_prompt",
        title: "Titular conciso y memorable para [tipo de producto/servicio]",
        slug: "titular-conciso-memorable",
        summary: "Escribe un titular conciso y memorable para [tipo de producto/servicio].",
        body_markdown: "Escribe un titular conciso y memorable para [tipo de producto/servicio].",
        prompt_text: "Escribe un titular conciso y memorable para [tipo de producto/servicio].",
        category: "Marketing y publicidad",
        level: "beginner",
        is_published: true,
        is_featured: false,
        paywall_level: "free_preview",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        tags: [{ id: "t-copy", name: "Copy", slug: "copy" }]
    },
    {
        id: "csv-3",
        type: "text_prompt",
        title: "Breve texto publicitario para aplicación combinada de redes sociales y finanzas",
        slug: "texto-publicitario-app-combinada",
        summary: "Texto publicitario directo al grano para una app multi-función.",
        body_markdown: "Escribe un breve texto publicitario para una aplicación que combina las funciones de aplicaciones como Instagram, WhatsApp, Venmo y Tik Tok en un solo lugar. Utiliza un lenguaje rápido y conciso, similar al de Apple, que atraiga a un público más joven. Ve directo al grano: no pierdas el tiempo.",
        prompt_text: "Escribe un breve texto publicitario para una aplicación que combina las funciones de aplicaciones como Instagram, WhatsApp, Venmo y Tik Tok en un solo lugar. Utiliza un lenguaje rápido y conciso, similar al de Apple, que atraiga a un público más joven. Ve directo al grano: no pierdas el tiempo.",
        category: "Marketing y publicidad",
        level: "beginner",
        is_published: true,
        is_featured: false,
        paywall_level: "free_preview",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        tags: [{ id: "t-copy", name: "Copy", slug: "copy" }]
    },
    {
        id: "csv-4",
        type: "text_prompt",
        title: "Asuntos de correo electrónico para venta flash de curso en línea de creación de contenidos de IA",
        slug: "asuntos-email-venta-flash-ia",
        summary: "10 líneas de asunto de correo electrónico para una venta flash del 50%.",
        body_markdown: "Escribe 10 líneas de asunto de correo electrónico para una venta flash del 50% de descuento en un curso online de creación de contenidos de IA. Ve directo al grano - no pierdas el tiempo.",
        prompt_text: "Escribe 10 líneas de asunto de correo electrónico para una venta flash del 50% de descuento en un curso online de creación de contenidos de IA. Ve directo al grano - no pierdas el tiempo.",
        category: "Marketing y publicidad",
        level: "beginner",
        is_published: true,
        is_featured: false,
        paywall_level: "free_preview",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        tags: [{ id: "t-copy", name: "Copy", slug: "copy" }]
    },
    {
        id: "csv-5",
        type: "text_prompt",
        title: "Anuncio publicitario para un restaurante vegano",
        slug: "anuncio-restaurante-vegano",
        summary: "Anuncio creativo y atractivo para un restaurante vegano.",
        body_markdown: "Escribe un anuncio publicitario para un restaurante vegano que resalte los beneficios de una dieta vegana y la calidad de los ingredientes utilizados. Utiliza un lenguaje creativo y atractivo que haga que los clientes potenciales se sientan atraídos por el restaurante y su oferta gastronómica.",
        prompt_text: "Escribe un anuncio publicitario para un restaurante vegano que resalte los beneficios de una dieta vegana y la calidad de los ingredientes utilizados. Utiliza un lenguaje creativo y atractivo que haga que los clientes potenciales se sientan atraídos por el restaurante y su oferta gastronómica.",
        category: "Marketing y publicidad",
        level: "beginner",
        is_published: true,
        is_featured: false,
        paywall_level: "free_preview",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        tags: [{ id: "t-copy", name: "Copy", slug: "copy" }]
    },
    {
        id: "csv-6",
        type: "text_prompt",
        title: "Líneas de asunto para promoción de marca de ropa",
        slug: "lineas-asunto-promocion-ropa",
        summary: "10 líneas de asunto de correo electrónico para una marca de moda.",
        body_markdown: "Escribe 10 líneas de asunto de correo electrónico para una promoción de una marca de ropa. Ve directo al grano, utiliza un lenguaje atractivo y no pierdas el tiempo.",
        prompt_text: "Escribe 10 líneas de asunto de correo electrónico para una promoción de una marca de ropa. Ve directo al grano, utiliza un lenguaje atractivo y no pierdas el tiempo.",
        category: "Marketing y publicidad",
        level: "beginner",
        is_published: true,
        is_featured: false,
        paywall_level: "free_preview",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        tags: [{ id: "t-copy", name: "Copy", slug: "copy" }]
    },
    {
        id: "csv-7",
        type: "text_prompt",
        title: "Reseña de producto [tipo de producto] desde la perspectiva de [tipo de cliente]",
        slug: "resena-producto-perspectiva-cliente",
        summary: "Reseña de producto con voz de Generación Z.",
        body_markdown: "Escribe una reseña de un producto [tipo de producto] desde la perspectiva de [tipo de cliente]. No suenes demasiado promocional. Escribe como un miembro de la Generación Z.",
        prompt_text: "Escribe una reseña de un producto [tipo de producto] desde la perspectiva de [tipo de cliente]. No suenes demasiado promocional. Escribe como un miembro de la Generación Z.",
        category: "Reseñas de productos",
        level: "beginner",
        is_published: true,
        is_featured: false,
        paywall_level: "free_preview",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        tags: [{ id: "t-copy", name: "Copy", slug: "copy" }]
    },
    {
        id: "csv-8",
        type: "text_prompt",
        title: "Descripción de tienda en línea de bolsa grande de palomitas de maíz veganas",
        slug: "descripcion-tienda-palomitas-veganas",
        summary: "Descripción de e-commerce rápida y concisa.",
        body_markdown: "Escribe la descripción de una tienda de comercio electrónico para un juego de mesa divertido y educativo para niños. Utiliza un lenguaje rápido y conciso que atraiga tanto a padres como a niños. Destaca su valor educativo y no suenes demasiado promocional.",
        prompt_text: "Escribe la descripción de una tienda de comercio electrónico para un juego de mesa divertido y educativo para niños. Utiliza un lenguaje rápido y conciso que atraiga tanto a padres como a niños. Destaca su valor educativo y no suenes demasiado promocional.",
        category: "Reseñas de productos",
        level: "beginner",
        is_published: true,
        is_featured: false,
        paywall_level: "free_preview",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        tags: [{ id: "t-copy", name: "Copy", slug: "copy" }]
    },
    {
        id: "csv-9",
        type: "text_prompt",
        title: "Reseña de producto de belleza para adolescentes",
        slug: "resena-producto-belleza-adolescentes",
        summary: "Reseña de producto de belleza para piel sensible.",
        body_markdown: "Escribe una reseña de un producto de belleza desde la perspectiva de una adolescente con piel sensible. No suenes demasiado promocional y utiliza un lenguaje cercano y juvenil.",
        prompt_text: "Escribe una reseña de un producto de belleza desde la perspectiva de una adolescente con piel sensible. No suenes demasiado promocional y utiliza un lenguaje cercano y juvenil.",
        category: "Reseñas de productos",
        level: "beginner",
        is_published: true,
        is_featured: false,
        paywall_level: "free_preview",
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        tags: [{ id: "t-copy", name: "Copy", slug: "copy" }]
    }
];
