-- Generated by import_user_csv.js at 2026-01-23T16:29:31.987Z


-- Category: Textos de promoción
INSERT INTO public.tags (name, slug) VALUES ('Textos de promoción', 'textos-de-promoci-n') ON CONFLICT (slug) DO NOTHING;

-- Category: Marketing y publicidad
INSERT INTO public.tags (name, slug) VALUES ('Marketing y publicidad', 'marketing-y-publicidad') ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.content (
  type, title, slug, summary, body_markdown, category, level, is_published, is_featured, paywall_level, created_at
) VALUES (
  'prompt',
  'producto]',
  'producto',
  'Imported from 750PROMPT.csv',
  'Escribe un pie de foto de Instagram para un post promocional de [tipo de producto]. Utiliza un lenguaje amigable y humano que atraiga a [tipo de público]. Destaca las cualidades únicas de [tipo de producto], utiliza emojis de muestra y no suenes demasiado promocional.',
  'Marketing y publicidad',
  'beginner',
  true,
  false,
  'free_preview',
  NOW()
) ON CONFLICT (slug) DO UPDATE SET 
  body_markdown = EXCLUDED.body_markdown,
  category = EXCLUDED.category;

INSERT INTO public.content_tags (content_id, tag_id)
SELECT c.id, t.id 
FROM public.content c, public.tags t 
WHERE c.slug = 'producto' AND t.slug = 'marketing-y-publicidad'
ON CONFLICT DO NOTHING;

INSERT INTO public.content (
  type, title, slug, summary, body_markdown, category, level, is_published, is_featured, paywall_level, created_at
) VALUES (
  'prompt',
  'producto/servicio]',
  'producto-servicio',
  'Imported from 750PROMPT.csv',
  'producto/servicio].',
  'Marketing y publicidad',
  'beginner',
  true,
  false,
  'free_preview',
  NOW()
) ON CONFLICT (slug) DO UPDATE SET 
  body_markdown = EXCLUDED.body_markdown,
  category = EXCLUDED.category;

INSERT INTO public.content_tags (content_id, tag_id)
SELECT c.id, t.id 
FROM public.content c, public.tags t 
WHERE c.slug = 'producto-servicio' AND t.slug = 'marketing-y-publicidad'
ON CONFLICT DO NOTHING;

INSERT INTO public.content (
  type, title, slug, summary, body_markdown, category, level, is_published, is_featured, paywall_level, created_at
) VALUES (
  'prompt',
  'finanzas',
  'finanzas',
  'Imported from 750PROMPT.csv',
  'Escribe un breve texto publicitario para una aplicación que combina las funciones de aplicaciones como Instagram, WhatsApp, Venmo y Tik Tok en un solo lugar. Utiliza un lenguaje rápido y conciso, similar al de Apple, que atraiga a un público más joven. Ve directo al grano: no pierdas el tiempo.',
  'Marketing y publicidad',
  'beginner',
  true,
  false,
  'free_preview',
  NOW()
) ON CONFLICT (slug) DO UPDATE SET 
  body_markdown = EXCLUDED.body_markdown,
  category = EXCLUDED.category;

INSERT INTO public.content_tags (content_id, tag_id)
SELECT c.id, t.id 
FROM public.content c, public.tags t 
WHERE c.slug = 'finanzas' AND t.slug = 'marketing-y-publicidad'
ON CONFLICT DO NOTHING;

INSERT INTO public.content (
  type, title, slug, summary, body_markdown, category, level, is_published, is_featured, paywall_level, created_at
) VALUES (
  'prompt',
  'IA',
  'ia',
  'Imported from 750PROMPT.csv',
  'tiempo.',
  'Marketing y publicidad',
  'beginner',
  true,
  false,
  'free_preview',
  NOW()
) ON CONFLICT (slug) DO UPDATE SET 
  body_markdown = EXCLUDED.body_markdown,
  category = EXCLUDED.category;

INSERT INTO public.content_tags (content_id, tag_id)
SELECT c.id, t.id 
FROM public.content c, public.tags t 
WHERE c.slug = 'ia' AND t.slug = 'marketing-y-publicidad'
ON CONFLICT DO NOTHING;

INSERT INTO public.content (
  type, title, slug, summary, body_markdown, category, level, is_published, is_featured, paywall_level, created_at
) VALUES (
  'prompt',
  'vegano',
  'vegano',
  'Imported from 750PROMPT.csv',
  'gastronómica.',
  'Marketing y publicidad',
  'beginner',
  true,
  false,
  'free_preview',
  NOW()
) ON CONFLICT (slug) DO UPDATE SET 
  body_markdown = EXCLUDED.body_markdown,
  category = EXCLUDED.category;

INSERT INTO public.content_tags (content_id, tag_id)
SELECT c.id, t.id 
FROM public.content c, public.tags t 
WHERE c.slug = 'vegano' AND t.slug = 'marketing-y-publicidad'
ON CONFLICT DO NOTHING;

INSERT INTO public.content (
  type, title, slug, summary, body_markdown, category, level, is_published, is_featured, paywall_level, created_at
) VALUES (
  'prompt',
  'ropa',
  'ropa',
  'Imported from 750PROMPT.csv',
  'Escribe 10 líneas de asunto de correo electrónico para una promoción de una marca de ropa. Ve directo al grano, utiliza un lenguaje atractivo y no pierdas el tiempo.',
  'Marketing y publicidad',
  'beginner',
  true,
  false,
  'free_preview',
  NOW()
) ON CONFLICT (slug) DO UPDATE SET 
  body_markdown = EXCLUDED.body_markdown,
  category = EXCLUDED.category;

INSERT INTO public.content_tags (content_id, tag_id)
SELECT c.id, t.id 
FROM public.content c, public.tags t 
WHERE c.slug = 'ropa' AND t.slug = 'marketing-y-publicidad'
ON CONFLICT DO NOTHING;

-- Category: Reseñas de productos
INSERT INTO public.tags (name, slug) VALUES ('Reseñas de productos', 'rese-as-de-productos') ON CONFLICT (slug) DO NOTHING;

INSERT INTO public.content (
  type, title, slug, summary, body_markdown, category, level, is_published, is_featured, paywall_level, created_at
) VALUES (
  'prompt',
  'cliente]',
  'cliente',
  'Imported from 750PROMPT.csv',
  'Z.',
  'Reseñas de productos',
  'beginner',
  true,
  false,
  'free_preview',
  NOW()
) ON CONFLICT (slug) DO UPDATE SET 
  body_markdown = EXCLUDED.body_markdown,
  category = EXCLUDED.category;

INSERT INTO public.content_tags (content_id, tag_id)
SELECT c.id, t.id 
FROM public.content c, public.tags t 
WHERE c.slug = 'cliente' AND t.slug = 'rese-as-de-productos'
ON CONFLICT DO NOTHING;

INSERT INTO public.content (
  type, title, slug, summary, body_markdown, category, level, is_published, is_featured, paywall_level, created_at
) VALUES (
  'prompt',
  'veganas',
  'veganas',
  'Imported from 750PROMPT.csv',
  'promocional.',
  'Reseñas de productos',
  'beginner',
  true,
  false,
  'free_preview',
  NOW()
) ON CONFLICT (slug) DO UPDATE SET 
  body_markdown = EXCLUDED.body_markdown,
  category = EXCLUDED.category;

INSERT INTO public.content_tags (content_id, tag_id)
SELECT c.id, t.id 
FROM public.content c, public.tags t 
WHERE c.slug = 'veganas' AND t.slug = 'rese-as-de-productos'
ON CONFLICT DO NOTHING;

INSERT INTO public.content (
  type, title, slug, summary, body_markdown, category, level, is_published, is_featured, paywall_level, created_at
) VALUES (
  'prompt',
  'adolescentes',
  'adolescentes',
  'Imported from 750PROMPT.csv',
  'juvenil.',
  'Reseñas de productos',
  'beginner',
  true,
  false,
  'free_preview',
  NOW()
) ON CONFLICT (slug) DO UPDATE SET 
  body_markdown = EXCLUDED.body_markdown,
  category = EXCLUDED.category;

INSERT INTO public.content_tags (content_id, tag_id)
SELECT c.id, t.id 
FROM public.content c, public.tags t 
WHERE c.slug = 'adolescentes' AND t.slug = 'rese-as-de-productos'
ON CONFLICT DO NOTHING;
