
const fs = require('fs');

async function main() {
    const url = 'https://raw.githubusercontent.com/jimmylv/awesome-nano-banana/main/README.md';

    console.log(`Fetching ${url}...`);
    const response = await fetch(url);
    const text = await response.text();

    // Extract cases
    // Looking for patterns like:
    // ### Case 100: Title (by [@author](...))
    // ...
    // Prompt
    // ```
    // content
    // ```

    const cases = [];
    const lines = text.split('\n');
    let currentCase = null;
    let inPromptBlock = false;

    for (let i = 0; i < lines.length; i++) {
        const line = lines[i].trim();

        // Match Case Header: ### Case X: Title (by ...)
        const caseMatch = line.match(/^### Case (\d+): (.+?) \(by \[@?(.+?)\]/);
        if (caseMatch) {
            if (currentCase) {
                // Push previous case if it has a prompt
                if (currentCase.prompt) cases.push(currentCase);
            }
            currentCase = {
                number: caseMatch[1],
                title: caseMatch[2].trim(),
                author: caseMatch[3].trim(),
                prompt: ''
            };
            inPromptBlock = false;
            continue;
        }

        // Also handle shared headers like: ### Case 99: ... + Case 98: ...
        // This script is a bit simple, it might miss "shared" header lines if they are not split. 
        // The previous view_content_chunk showed "Case 99... + Case 98..." in standard markdown, 
        // but looking at raw text structure is safer. 
        // Let's refine the regex to catch "Case \d+" generally if the previous stricter one fails? 
        // Actually the raw markdown usually has separate sections or at least clear delimiters.
        // Let's stick to valid distinct headers first.

        // Check for "Prompt" label
        if (currentCase && line.toLowerCase() === 'prompt') {
            // The next block should be the code block
            continue;
        }

        if (currentCase && line.startsWith('```')) {
            if (inPromptBlock) {
                // End of prompt
                inPromptBlock = false;
            } else {
                // Start of prompt
                inPromptBlock = true;
            }
            continue;
        }

        if (inPromptBlock && currentCase) {
            currentCase.prompt += line + '\n';
        }
    }
    // Push last case
    if (currentCase && currentCase.prompt) {
        cases.push(currentCase);
    }

    console.log(`Found ${cases.length} cases.`);

    // Generate SQL
    let sql = `-- Generated by import_nano_banana.js at ${new Date().toISOString()}\n\n`;

    // 1. Create Tag if not exists
    sql += `
-- Ensure 'Nano Banana' tag exists
INSERT INTO public.tags (name, slug) 
VALUES ('Nano Banana', 'nano-banana') 
ON CONFLICT (slug) DO NOTHING;
\n`;

    // 2. Insert Content
    for (const c of cases) {
        const slug = `nano-banana-case-${c.number}`;
        const title = `Case ${c.number}: ${c.title}`;
        // Escape single quotes
        const safeTitle = title.replace(/'/g, "''");
        const safePrompt = c.prompt.trim().replace(/'/g, "''");
        const safeAuthor = c.author.replace(/'/g, "''");

        // Determine author credit/summary
        const summary = `Created by ${safeAuthor}. Imported from Awesome Nano Banana.`;

        // We'll put the prompt in 'body_markdown' but maybe wrapped or just raw? 
        // The schema says 'body_markdown'. Usually that's the full article. 
        // For a prompt library, maybe the body IS the prompt? 
        // Let's wrap it in values needed for the content table.
        // type = 'prompt'

        sql += `
INSERT INTO public.content (
  type, title, slug, summary, body_markdown, category, level, is_published, is_featured, paywall_level, created_at
) VALUES (
  'prompt',
  '${safeTitle}',
  '${slug}',
  '${summary}',
  '${safePrompt}',
  'Generative AI',
  'intermediate',
  true,
  false,
  'free_preview',
  NOW()
) ON CONFLICT (slug) DO UPDATE SET 
  body_markdown = EXCLUDED.body_markdown,
  summary = EXCLUDED.summary;
`;

        // 3. Link Tag
        sql += `
INSERT INTO public.content_tags (content_id, tag_id)
SELECT c.id, t.id 
FROM public.content c, public.tags t 
WHERE c.slug = '${slug}' AND t.slug = 'nano-banana'
ON CONFLICT DO NOTHING;
`;
    }

    fs.writeFileSync('imported_prompts.sql', sql);
    console.log('Successfully generated imported_prompts.sql');
}

main().catch(console.error);
