const fs = require('fs');
const path = require('path');

async function main() {
    const csvPath = 'C:\\Users\\USER\\Downloads\\750PROMPT.csv';
    const outputPath = 'user_prompts.sql';

    console.log(`Reading CSV from ${csvPath}...`);
    // Read with 'binary' then convert or just handle as Buffer to detect encoding
    const buffer = fs.readFileSync(csvPath);

    // Check for UTF-8 BOM
    let content;
    if (buffer[0] === 0xEF && buffer[1] === 0xBB && buffer[2] === 0xBF) {
        content = buffer.toString('utf8', 3);
    } else {
        // Many Excel CSVs are Latin1/Win1252
        // Let's try to detect based on common Spanish characters
        const strUtf8 = buffer.toString('utf8');
        if (strUtf8.includes('Ã')) {
            // Likely was Latin1 read as UTF-8 incorrectly. 
            // However, the previous 'utf8' read showed "Ã³" which means the file IS UTF-8 but the terminal/reader interpreted it as Latin1.
            // Wait, "Ã³" (UTF-8 0xC3 0xB3) is "ó" in UTF-8. 
            // If fs.readFileSync(..., 'utf8') gave me "Ã³", then the file might actually be encoded as UTF-8 but double encoded? 
            // No, it just means the log output show it that way. 
            content = strUtf8;
        } else {
            content = buffer.toString('utf8');
        }
    }

    const lines = content.split(/\r?\n/);

    let sql = `-- Generated by import_user_csv.js at ${new Date().toISOString()}\n\n`;
    let currentCategory = 'General';
    let count = 0;

    const seenSlugs = new Set();

    console.log(`Processing ${lines.length} potential lines...`);

    for (let i = 0; i < lines.length; i++) {
        const line = lines[i].trim();
        if (!line) continue;

        // Skip rows that look like empty headers or noise
        if (line.startsWith(',,') || line === ',') continue;

        // Detect category headers
        // The pattern seems to be: ,Category Name,
        const categoryMatch = line.match(/^,([^,]+),?$/);
        if (categoryMatch && !line.includes('FINALIDAD')) {
            currentCategory = categoryMatch[1].trim();
            console.log(`[Category] ${currentCategory}`);

            const tagSlug = currentCategory.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
            sql += `\n-- Category: ${currentCategory}\n`;
            sql += `INSERT INTO public.tags (name, slug) VALUES ('${currentCategory.replace(/'/g, "''")}', '${tagSlug}') ON CONFLICT (slug) DO NOTHING;\n`;
            continue;
        }

        // Detect data rows (Title, Prompt)
        if (line.includes('FINALIDAD,PROMPT')) continue;

        // More robust CSV line split (handles quotes and commas inside quotes)
        // regex source: https://stackoverflow.com/questions/11456850/split-a-text-line-by-commas-but-ignore-commas-within-double-quotes
        const parts = line.match(/(".*?"|[^",\s]+)(?=\s*,|\s*$)/g);

        // Sometimes lines might not match the regex if they are messy. 
        // Let's try a fallback split if parts is null
        let title, promptText;
        if (parts && parts.length >= 2) {
            title = parts[0].trim().replace(/^"|"$/g, '').replace(/""/g, '"');
            promptText = parts[1].trim().replace(/^"|"$/g, '').replace(/""/g, '"');
        } else {
            // Fallback for non-standard lines
            const simpleSplit = line.split(',');
            if (simpleSplit.length >= 2) {
                title = simpleSplit[0].trim();
                promptText = simpleSplit.slice(1).join(',').trim();
            }
        }

        if (title && promptText && title !== 'FINALIDAD') {
            const baseSlug = title.toLowerCase()
                .replace(/[^a-z0-9]+/g, '-')
                .replace(/(^-|-$)/g, '')
                .slice(0, 50);

            let slug = baseSlug || 'prompt-' + count;
            let counter = 1;
            while (seenSlugs.has(slug)) {
                slug = `${baseSlug.slice(0, 45)}-${counter++}`;
            }
            seenSlugs.add(slug);

            const safeTitle = title.replace(/'/g, "''");
            const safePrompt = promptText.replace(/'/g, "''");
            const tagSlug = currentCategory.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

            sql += `
INSERT INTO public.content (
  type, title, slug, summary, body_markdown, category, level, is_published, is_featured, paywall_level, created_at
) VALUES (
  'prompt',
  '${safeTitle}',
  '${slug}',
  'Imported from 750PROMPT.csv',
  '${safePrompt}',
  '${currentCategory.replace(/'/g, "''")}',
  'beginner',
  true,
  false,
  'free_preview',
  NOW()
) ON CONFLICT (slug) DO UPDATE SET 
  body_markdown = EXCLUDED.body_markdown,
  category = EXCLUDED.category;

INSERT INTO public.content_tags (content_id, tag_id)
SELECT c.id, t.id 
FROM public.content c, public.tags t 
WHERE c.slug = '${slug}' AND t.slug = '${tagSlug}'
ON CONFLICT DO NOTHING;
`;
            count++;
        }
    }

    fs.writeFileSync(outputPath, sql);
    console.log(`Successfully generated ${outputPath} with ${count} prompts.`);
}

main().catch(console.error);
